[2025-05-23 15:06:28] [INFO] Starting HeyGen bot...
[2025-05-23 15:06:49] [INFO] Navigated to login page.
[2025-05-23 15:07:20] [ERROR] Exception occurred: Page.click: Timeout 30000ms exceeded.
Call log:
  - waiting for locator("button[type=\"submit\"]")

Traceback (most recent call last):
  File "C:\Users\mogen\Projects\python\CHATGPT\MyAvatar\heygen_bot\heygen_bot.py", line 34, in download_video_and_docs
    page.click('button[type="submit"]')
  File "C:\Users\mogen\Projects\python\CHATGPT\MyAvatar\venv\Lib\site-packages\playwright\sync_api\_generated.py", line 9932, in click
    self._sync(
  File "C:\Users\mogen\Projects\python\CHATGPT\MyAvatar\venv\Lib\site-packages\playwright\_impl\_sync_base.py", line 115, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "C:\Users\mogen\Projects\python\CHATGPT\MyAvatar\venv\Lib\site-packages\playwright\_impl\_page.py", line 833, in click
    return await self._main_frame.click(**locals_to_params(locals()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mogen\Projects\python\CHATGPT\MyAvatar\venv\Lib\site-packages\playwright\_impl\_frame.py", line 488, in click
    await self._channel.send("click", locals_to_params(locals()))
  File "C:\Users\mogen\Projects\python\CHATGPT\MyAvatar\venv\Lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mogen\Projects\python\CHATGPT\MyAvatar\venv\Lib\site-packages\playwright\_impl\_connection.py", line 528, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Page.click: Timeout 30000ms exceeded.
Call log:
  - waiting for locator("button[type=\"submit\"]")


[2025-05-23 15:08:06] [INFO] Starting HeyGen bot...
[2025-05-23 15:08:18] [INFO] Navigated to login page.
[2025-05-23 15:08:48] [ERROR] Exception occurred: Page.click: Timeout 30000ms exceeded.
Call log:
  - waiting for locator("button[type=\"submit\"]")

Traceback (most recent call last):
  File "C:\Users\mogen\Projects\python\CHATGPT\MyAvatar\heygen_bot\heygen_bot.py", line 34, in download_video_and_docs
    page.click('button[type="submit"]')
  File "C:\Users\mogen\Projects\python\CHATGPT\MyAvatar\venv\Lib\site-packages\playwright\sync_api\_generated.py", line 9932, in click
    self._sync(
  File "C:\Users\mogen\Projects\python\CHATGPT\MyAvatar\venv\Lib\site-packages\playwright\_impl\_sync_base.py", line 115, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "C:\Users\mogen\Projects\python\CHATGPT\MyAvatar\venv\Lib\site-packages\playwright\_impl\_page.py", line 833, in click
    return await self._main_frame.click(**locals_to_params(locals()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mogen\Projects\python\CHATGPT\MyAvatar\venv\Lib\site-packages\playwright\_impl\_frame.py", line 488, in click
    await self._channel.send("click", locals_to_params(locals()))
  File "C:\Users\mogen\Projects\python\CHATGPT\MyAvatar\venv\Lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mogen\Projects\python\CHATGPT\MyAvatar\venv\Lib\site-packages\playwright\_impl\_connection.py", line 528, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Page.click: Timeout 30000ms exceeded.
Call log:
  - waiting for locator("button[type=\"submit\"]")


[2025-05-23 15:10:24] [INFO] Starting HeyGen bot...
[2025-05-23 15:10:34] [INFO] Navigated to login page.
[2025-05-23 15:11:05] [ERROR] Exception occurred: Page.click: Timeout 30000ms exceeded.
Call log:
  - waiting for locator("button[type=\"submit\"]")

Traceback (most recent call last):
  File "C:\Users\mogen\Projects\python\CHATGPT\MyAvatar\heygen_bot\heygen_bot.py", line 34, in download_video_and_docs
    page.click('button[type="submit"]')
  File "C:\Users\mogen\Projects\python\CHATGPT\MyAvatar\venv\Lib\site-packages\playwright\sync_api\_generated.py", line 9932, in click
    self._sync(
  File "C:\Users\mogen\Projects\python\CHATGPT\MyAvatar\venv\Lib\site-packages\playwright\_impl\_sync_base.py", line 115, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "C:\Users\mogen\Projects\python\CHATGPT\MyAvatar\venv\Lib\site-packages\playwright\_impl\_page.py", line 833, in click
    return await self._main_frame.click(**locals_to_params(locals()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mogen\Projects\python\CHATGPT\MyAvatar\venv\Lib\site-packages\playwright\_impl\_frame.py", line 488, in click
    await self._channel.send("click", locals_to_params(locals()))
  File "C:\Users\mogen\Projects\python\CHATGPT\MyAvatar\venv\Lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mogen\Projects\python\CHATGPT\MyAvatar\venv\Lib\site-packages\playwright\_impl\_connection.py", line 528, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Page.click: Timeout 30000ms exceeded.
Call log:
  - waiting for locator("button[type=\"submit\"]")


